version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DHASH_PASSWORD=stringtohashpassword
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html/
    links:
      - db

  db:
    image: mariadb:10.3
    restart: always
    volumes:
      - ./data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: pass

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1